### ISSUE TITLE
Error in WFO.match, WFO.prepare, and WFO.url (version 1.11) with version of R > 4.2.0

### ISSUE THREAD

**Issue by amael-ls** [cran/WorldFlora#1]
Since the version R 4.2.0, Calling if() or while() with a condition of length greater than one gives an error rather than a warning. Consequently, environment variable _R_CHECK_LENGTH_1_CONDITION_ no longer has any effect. [See here for information, scroll down to 'Changes in R 4.2.0'](https://cran.r-project.org/doc/manuals/r-devel/NEWS.html). Therefore, the line:
- 23 of the function WFO.match (version 1.11 of the package)
- 15 of the function WFO.prepare (version 1.11 of the package)
- 5 of the function WFO.url
which all uses:
`if (class(WHATEVER) %in% c("data.frame") == FALSE) {spec.data <- data.frame(spec.name = spec.data)}`

will throw an error when `WHATEVER` is a `data.table`.

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!

**Comment by amael-ls** [comment]
Hi, many thanks! I contacted the maintainer, wait and see for the next version
