### ISSUE TITLE
exclude.infraspecific = TRUE error

### ISSUE THREAD

**Issue by msedaghatpour** [cran/WorldFlora#4]
exclude.infraspecific = TRUE from WFO.match() is returning the error:
Error in if (WFO.out[i, "verbatimTaxonRank"] %in% infraspecific.excluded) { : 
  argument is of length zero

Here is my code: 
###
WCVP <- fread(paste0(
  "~/Desktop/update_flora_final/data/wcvp_20230410/wcvp_names.csv"),
  encoding="UTF-8")

WCVP.data <- new.backbone(WCVP, 
                          taxonID="plant_name_id",
                          scientificName="taxon_name",
                          scientificNameAuthorship="taxon_authors",
                          acceptedNameUsageID = "accepted_plant_name_id",
                          taxonomicStatus = "taxon_status")

WFO_WCVP_output <- WFO.match(
  spec.data = infra,
  WFO.data = WCVP.data,
  exclude.infraspecific = TRUE,
  counter = 1)
###

My goal is to get the authorities for a list of accepted species rank names
WCVP can be downloaded from https://powo.science.kew.org

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
